version: "3.9" # Specify Docker Compose version

services:
  mongo:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "27017:27017" # Map container port 27017 to host port 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fdj # Optional: Set root user (adjust password if needed)
      - MONGO_INITDB_ROOT_PASSWORD=fdj # Optional: Set root password
    volumes:
      - ./db/mongo-dump:/mongo-dump

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://fdj:fdj@mongo:27017

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=fdj
      - ME_CONFIG_BASICAUTH_PASSWORD=fdj
      - ME_CONFIG_MONGODB_ADMINUSERNAME=fdj
      - ME_CONFIG_MONGODB_ADMINPASSWORD=fdj
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - 8081:8081
    depends_on:
      - mongo
